import type { BrandMarketingData } from "@/types/brand-marketing";

export const brandMarketingMockVi: BrandMarketingData = {
  brandStrategy: [
    {
      id: "bm-s-1",
      name: "Định vị thương hiệu Bông Sen Vàng 2026 — Di sản YHCT toàn chuỗi",
      status: "Đang triển khai",
      metric: "Nhận diện thương hiệu +12 điểm",
      period: "2026",
      owner: "Brand & Corporate",
    },
    {
      id: "bm-s-2",
      name: "Hệ visual identity — logo, màu, typography đồng bộ 5 công ty con",
      status: "Hoàn tất",
      metric: "100% guideline",
      period: "Q1/2026",
      owner: "Creative hub",
    },
    {
      id: "bm-s-3",
      name: "Thông điệu chủ đạo: Tinh hoa thảo dược — Truyền thống — Tin cậy",
      status: "Đang chạy",
      metric: "Áp dụng 36 touchpoint",
      period: "Liên tục",
      owner: "Brand strategy",
    },
    {
      id: "bm-s-4",
      name: "Architecture thương hiệu: Master brand + sub-brand Yogi Food, TST, Thần Trà",
      status: "Theo dõi",
      metric: "5 sub-brand",
      period: "2026",
      owner: "Brand architecture",
    },
    {
      id: "bm-s-5",
      name: "Nghiên cứu thị trường — nhận thức thương hiệu vùng Bắc / Trung / Nam",
      status: "Kế hoạch",
      metric: "3.200 mẫu",
      period: "T3/2026",
      owner: "Insights & Brand",
    },
  ],
  campaigns: [
    {
      id: "bm-c-1",
      name: "Chiến dịch Tết — Di sản sum vầy (toàn chuỗi)",
      status: "Hoàn tất",
      metric: "Reach 8.2M · SOV 24%",
      period: "T1/2026",
      owner: "Brand activation",
    },
    {
      id: "bm-c-2",
      name: "Always-on: Sống khỏe từ thiên nhiên — video & OOH",
      status: "Đang chạy",
      metric: "CPM ₫42K",
      period: "Q1–Q2/2026",
      owner: "Media buying",
    },
    {
      id: "bm-c-3",
      name: "Ra mắt sub-brand Thượng Sơn Trà — teaser & launch event",
      status: "Đang chạy",
      metric: "PR 120 bài · 2.1M view",
      period: "Tháng 3–4/2026",
      owner: "TST brand team",
    },
    {
      id: "bm-c-4",
      name: "Yogi Food — Chiến dịch dinh dưỡng chủ động (school & office)",
      status: "Kế hoạch",
      metric: "Ngân sách ₫1.2 tỷ",
      period: "Q2/2026",
      owner: "Yogi Food marketing",
    },
    {
      id: "bm-c-5",
      name: "Heritage herbs — Roadshow 12 tỉnh YHCT",
      status: "Theo dõi",
      metric: "18.000 khách tham dự",
      period: "T4–T6/2026",
      owner: "Field brand",
    },
  ],
  channels: [
    {
      id: "bm-ch-1",
      name: "Website tập đoàn + landing 5 thương hiệu con",
      status: "Đang chạy",
      metric: "Traffic 420K/th",
      period: "2026",
      owner: "Digital brand",
    },
    {
      id: "bm-ch-2",
      name: "Social master: Facebook, TikTok, YouTube Bông Sen Vàng",
      status: "Đang chạy",
      metric: "Follower 1.1M tổng",
      period: "Liên tục",
      owner: "Social & content",
    },
    {
      id: "bm-ch-3",
      name: "Zalo OA thương hiệu — chăm sóc & mini-app",
      status: "Đang chạy",
      metric: "MAU 186K",
      period: "2026",
      owner: "CRM brand",
    },
    {
      id: "bm-ch-4",
      name: "OOH & transit — HCM, HN, ĐN (nhận diện master brand)",
      status: "Kế hoạch",
      metric: "248 điểm booking",
      period: "Q2/2026",
      owner: "OOH agency",
    },
    {
      id: "bm-ch-5",
      name: "In-store brand zone — chuẩn hóa POS toàn mạng 36 CH",
      status: "Theo dõi",
      metric: "Tuân thủ 92%",
      period: "Tháng 3/2026",
      owner: "Trade & VM",
    },
  ],
  partnerships: [
    {
      id: "bm-p-1",
      name: "Hợp tác Bệnh viện YHCT — chương trình giáo dục sức khỏe",
      status: "Đang chạy",
      metric: "12 BV tham gia",
      period: "2026",
      owner: "Partnership",
    },
    {
      id: "bm-p-2",
      name: "Đại sứ thương hiệu — chuyên gia YHCT & lifestyle",
      status: "Đang chạy",
      metric: "4 đại sứ · ER 4.8%",
      period: "Hợp đồng 12 tháng",
      owner: "Influencer hub",
    },
    {
      id: "bm-p-3",
      name: "Co-branding siêu thị MT — góc thảo dược di sản",
      status: "Kế hoạch",
      metric: "8 chuỗi MT",
      period: "Q2/2026",
      owner: "Trade marketing",
    },
    {
      id: "bm-p-4",
      name: "Sponsorship sự kiện văn hóa — Lễ hội thảo dược",
      status: "Theo dõi",
      metric: "Reach 1.4M",
      period: "T5/2026",
      owner: "Events",
    },
    {
      id: "bm-p-5",
      name: "Liên minh nội dung — podcast Sống xanh cùng BSV",
      status: "Đang chạy",
      metric: "24 tập · 8K listen/ep",
      period: "T2–T4/2026",
      owner: "Content studio",
    },
  ],
  budgetPerformance: [
    {
      id: "bm-b-1",
      name: "Ngân sách brand marketing 2026 — toàn tập đoàn",
      status: "Đang chạy",
      metric: "₫18.5 tỷ · tiêu 42%",
      period: "2026",
      owner: "FP&A & Brand",
    },
    {
      id: "bm-b-2",
      name: "Brand lift study — chiến dịch Tết & always-on",
      status: "Hoàn tất",
      metric: "Awareness +9%",
      period: "Q1/2026",
      owner: "Brand analytics",
    },
    {
      id: "bm-b-3",
      name: "ROI truyền thông số — so sánh Meta vs TikTok vs YouTube",
      status: "Theo dõi",
      metric: "ROAS 3.4× (Meta)",
      period: "Tháng 3/2026",
      owner: "Performance media",
    },
    {
      id: "bm-b-4",
      name: "Phân bổ ngân sách Q2 — ưu tiên TST launch & Yogi Food",
      status: "Kế hoạch",
      metric: "₫4.2 tỷ Q2",
      period: "Q2/2026",
      owner: "Brand steering",
    },
    {
      id: "bm-b-5",
      name: "Share of voice ngành YHCT & FMCG healthy",
      status: "Đang chạy",
      metric: "SOV 22% (+3pt)",
      period: "Rolling 90 ngày",
      owner: "Market intelligence",
    },
  ],
};
