import type { BrandMarketingData } from "@/types/brand-marketing";

export const brandMarketingMockZh: BrandMarketingData = {
  brandStrategy: [
    {
      id: "bm-s-1",
      name: "2026年金莲花草本集团定位 — 全链中医药传承",
      status: "进行中",
      metric: "品牌认知 +12分",
      period: "2026年",
      owner: "品牌与企业",
    },
    {
      id: "bm-s-2",
      name: "视觉识别系统 — 5家子公司统一logo/色彩/字体",
      status: "已完成",
      metric: "100%规范",
      period: "2026年Q1",
      owner: "创意中心",
    },
    {
      id: "bm-s-3",
      name: "主信息：草本精华 — 传承 — 信赖",
      status: "执行中",
      metric: "36个触点",
      period: "持续",
      owner: "品牌战略",
    },
    {
      id: "bm-s-4",
      name: "品牌架构：主品牌 + Yogi Food、上山茶、神茶子品牌",
      status: "监控中",
      metric: "5个子品牌",
      period: "2026年",
      owner: "品牌架构",
    },
    {
      id: "bm-s-5",
      name: "市场调研 — 北/中/南品牌认知",
      status: "计划中",
      metric: "3200样本",
      period: "2026年3月",
      owner: "洞察与品牌",
    },
  ],
  campaigns: [
    {
      id: "bm-c-1",
      name: "春节战役 — 传承团圆（全链）",
      status: "已完成",
      metric: "触达820万 · SOV 24%",
      period: "2026年Q1",
      owner: "品牌激活",
    },
    {
      id: "bm-c-2",
      name: "常播：自然健康生活 — 视频与户外",
      status: "进行中",
      metric: "CPM ₫42K",
      period: "2026年Q1–Q2",
      owner: "媒介采购",
    },
    {
      id: "bm-c-3",
      name: "上山茶子品牌发布 — 预告与发布会",
      status: "进行中",
      metric: "PR 120篇 · 210万播放",
      period: "2026年3–4月",
      owner: "上山茶品牌",
    },
    {
      id: "bm-c-4",
      name: "Yogi Food — 主动营养（校园与办公）",
      status: "计划中",
      metric: "预算12亿越南盾",
      period: "2026年Q2",
      owner: "Yogi Food营销",
    },
    {
      id: "bm-c-5",
      name: "传承草本 — 12省中医路演",
      status: "监控中",
      metric: "1.8万到场",
      period: "2026年4–6月",
      owner: "现场品牌",
    },
  ],
  channels: [
    {
      id: "bm-ch-1",
      name: "集团官网 + 5个子品牌落地页",
      status: "进行中",
      metric: "月访问42万",
      period: "2026年",
      owner: "数字品牌",
    },
    {
      id: "bm-ch-2",
      name: "主社媒：Facebook、TikTok、YouTube",
      status: "进行中",
      metric: "总粉丝110万",
      period: "持续",
      owner: "社媒与内容",
    },
    {
      id: "bm-ch-3",
      name: "Zalo OA品牌号 — 服务与小程序",
      status: "进行中",
      metric: "月活18.6万",
      period: "2026年",
      owner: "品牌CRM",
    },
    {
      id: "bm-ch-4",
      name: "户外与交通 — 胡志明、河内、岘港",
      status: "计划中",
      metric: "248个点位",
      period: "2026年Q2",
      owner: "户外代理",
    },
    {
      id: "bm-ch-5",
      name: "店内品牌区 — 36店POS标准化",
      status: "监控中",
      metric: "合规率92%",
      period: "2026年3月",
      owner: "贸易与陈列",
    },
  ],
  partnerships: [
    {
      id: "bm-p-1",
      name: "中医院合作 — 健康教育项目",
      status: "进行中",
      metric: "12家医院",
      period: "2026年",
      owner: "合作拓展",
    },
    {
      id: "bm-p-2",
      name: "品牌大使 — 中医专家与生活方式",
      status: "进行中",
      metric: "4位大使 · 互动率4.8%",
      period: "12个月合同",
      owner: "达人中心",
    },
    {
      id: "bm-p-3",
      name: "现代渠道联合 — 传承草本专柜",
      status: "计划中",
      metric: "8条MT链",
      period: "2026年Q2",
      owner: "贸易营销",
    },
    {
      id: "bm-p-4",
      name: "文化活动赞助 — 草药节",
      status: "监控中",
      metric: "触达140万",
      period: "2026年5月",
      owner: "活动",
    },
    {
      id: "bm-p-5",
      name: "内容联盟 — 与BSV绿色生活播客",
      status: "进行中",
      metric: "24集 · 8千收听/集",
      period: "2026年Q2–Q4",
      owner: "内容工作室",
    },
  ],
  budgetPerformance: [
    {
      id: "bm-b-1",
      name: "2026集团品牌营销预算",
      status: "进行中",
      metric: "185亿越南盾 · 已用42%",
      period: "2026年",
      owner: "财务与品牌",
    },
    {
      id: "bm-b-2",
      name: "品牌提升研究 — 春节与常播",
      status: "已完成",
      metric: "认知度 +9%",
      period: "2026年Q1",
      owner: "品牌分析",
    },
    {
      id: "bm-b-3",
      name: "数字ROI — Meta vs TikTok vs YouTube",
      status: "监控中",
      metric: "ROAS 3.4×（Meta）",
      period: "2026年3月",
      owner: "效果媒介",
    },
    {
      id: "bm-b-4",
      name: "Q2预算分配 — 优先上山茶与Yogi Food",
      status: "计划中",
      metric: "Q2 42亿越南盾",
      period: "2026年Q2",
      owner: "品牌决策",
    },
    {
      id: "bm-b-5",
      name: "声量份额 — 中医与健康快消",
      status: "进行中",
      metric: "SOV 22%（+3pt）",
      period: "滚动90天",
      owner: "市场情报",
    },
  ],
};
