import type { BrandMarketingData } from "@/types/brand-marketing";

export const brandMarketingMockEn: BrandMarketingData = {
  brandStrategy: [
    {
      id: "bm-s-1",
      name: "Golden Lotus Herbals 2026 positioning — chain-wide TCM heritage",
      status: "In progress",
      metric: "Brand awareness +12 pts",
      period: "2026",
      owner: "Brand & Corporate",
    },
    {
      id: "bm-s-2",
      name: "Visual identity system — logo, color, type across 5 subsidiaries",
      status: "Completed",
      metric: "100% guideline",
      period: "Q1/2026",
      owner: "Creative hub",
    },
    {
      id: "bm-s-3",
      name: "Master narrative: Herbal essence — Heritage — Trust",
      status: "Active",
      metric: "36 touchpoints",
      period: "Ongoing",
      owner: "Brand strategy",
    },
    {
      id: "bm-s-4",
      name: "Brand architecture: Master + Yogi Food, MST, Than Tra sub-brands",
      status: "Monitoring",
      metric: "5 sub-brands",
      period: "2026",
      owner: "Brand architecture",
    },
    {
      id: "bm-s-5",
      name: "Market study — brand awareness North / Central / South",
      status: "Planned",
      metric: "3,200 samples",
      period: "Mar/2026",
      owner: "Insights & Brand",
    },
  ],
  campaigns: [
    {
      id: "bm-c-1",
      name: "Lunar New Year — Heritage reunion (chain-wide)",
      status: "Completed",
      metric: "Reach 8.2M · SOV 24%",
      period: "Q1/2026",
      owner: "Brand activation",
    },
    {
      id: "bm-c-2",
      name: "Always-on: Healthy living from nature — video & OOH",
      status: "Active",
      metric: "CPM ₫42K",
      period: "Q1–Q2/2026",
      owner: "Media buying",
    },
    {
      id: "bm-c-3",
      name: "Thuong Son Tra sub-brand launch — teaser & event",
      status: "Active",
      metric: "120 PR pieces · 2.1M views",
      period: "Mar–Apr/2026",
      owner: "TST brand team",
    },
    {
      id: "bm-c-4",
      name: "Yogi Food — Proactive nutrition (school & office)",
      status: "Planned",
      metric: "Budget ₫1.2B",
      period: "Q2/2026",
      owner: "Yogi Food marketing",
    },
    {
      id: "bm-c-5",
      name: "Heritage herbs — 12-province TCM roadshow",
      status: "Monitoring",
      metric: "18,000 attendees",
      period: "Apr–Jun/2026",
      owner: "Field brand",
    },
  ],
  channels: [
    {
      id: "bm-ch-1",
      name: "Corporate website + 5 sub-brand landings",
      status: "Active",
      metric: "420K visits/mo",
      period: "2026",
      owner: "Digital brand",
    },
    {
      id: "bm-ch-2",
      name: "Master social: Facebook, TikTok, YouTube",
      status: "Active",
      metric: "1.1M total followers",
      period: "Ongoing",
      owner: "Social & content",
    },
    {
      id: "bm-ch-3",
      name: "Zalo OA brand — care & mini-app",
      status: "Active",
      metric: "186K MAU",
      period: "2026",
      owner: "Brand CRM",
    },
    {
      id: "bm-ch-4",
      name: "OOH & transit — HCM, Hanoi, Da Nang",
      status: "Planned",
      metric: "248 booked sites",
      period: "Q2/2026",
      owner: "OOH agency",
    },
    {
      id: "bm-ch-5",
      name: "In-store brand zones — 36 stores POS standard",
      status: "Monitoring",
      metric: "92% compliance",
      period: "Mar/2026",
      owner: "Trade & VM",
    },
  ],
  partnerships: [
    {
      id: "bm-p-1",
      name: "TCM hospital partnership — health education program",
      status: "Active",
      metric: "12 hospitals",
      period: "2026",
      owner: "Partnership",
    },
    {
      id: "bm-p-2",
      name: "Brand ambassadors — TCM experts & lifestyle",
      status: "Active",
      metric: "4 ambassadors · ER 4.8%",
      period: "12-month contract",
      owner: "Influencer hub",
    },
    {
      id: "bm-p-3",
      name: "MT co-branding — heritage herb corners",
      status: "Planned",
      metric: "8 MT chains",
      period: "Q2/2026",
      owner: "Trade marketing",
    },
    {
      id: "bm-p-4",
      name: "Cultural event sponsorship — herbal festival",
      status: "Monitoring",
      metric: "Reach 1.4M",
      period: "May/2026",
      owner: "Events",
    },
    {
      id: "bm-p-5",
      name: "Content alliance — Green Living with BSV podcast",
      status: "Active",
      metric: "24 eps · 8K listens/ep",
      period: "Q2–Q4/2026",
      owner: "Content studio",
    },
  ],
  budgetPerformance: [
    {
      id: "bm-b-1",
      name: "2026 group brand marketing budget",
      status: "Active",
      metric: "₫18.5B · 42% spent",
      period: "2026",
      owner: "FP&A & Brand",
    },
    {
      id: "bm-b-2",
      name: "Brand lift study — Tet & always-on",
      status: "Completed",
      metric: "Awareness +9%",
      period: "Q1/2026",
      owner: "Brand analytics",
    },
    {
      id: "bm-b-3",
      name: "Digital ROI — Meta vs TikTok vs YouTube",
      status: "Monitoring",
      metric: "ROAS 3.4× (Meta)",
      period: "Mar/2026",
      owner: "Performance media",
    },
    {
      id: "bm-b-4",
      name: "Q2 budget allocation — TST launch & Yogi Food priority",
      status: "Planned",
      metric: "₫4.2B Q2",
      period: "Q2/2026",
      owner: "Brand steering",
    },
    {
      id: "bm-b-5",
      name: "Share of voice — TCM & healthy FMCG",
      status: "Active",
      metric: "SOV 22% (+3pt)",
      period: "Rolling 90 days",
      owner: "Market intelligence",
    },
  ],
};
