import { buildCustomerCountChart } from "@/lib/customerCountChart";
import { buildRevenueChart } from "@/lib/dashboardRevenueChart";
import type { DashboardOverview } from "@/types/dashboard";

export const mockDashboardOverview: DashboardOverview = {
  highlight: {
    c1t: "Doanh thu tháng",
    c1v: "42.8",
    c1s: " tỷ",
    c2t: "Đơn hoàn tất",
    c2v: "18,420",
    c3t: "Tỷ lệ fill-rate",
    c3v: "94.2%",
  },
  kpis: [
    {
      id: "vendors",
      label: "Nhà cung cấp active",
      value: 1248,
      display: "1,248",
      growth: "+4.2% vs T-1",
      growthUp: true,
      spark: [3, 5, 4, 7, 6, 9, 8, 10],
    },
    {
      id: "customers",
      label: "Khách hàng CRM",
      value: 248420,
      display: "248.4K",
      growth: "+2.8% vs T-1",
      growthUp: true,
      spark: [4, 6, 5, 8, 7, 9, 10, 11],
    },
    {
      id: "signals",
      label: "Tín hiệu realtime",
      value: 324,
      display: "324",
      growth: "−1.1% vs T-1",
      growthUp: false,
      spark: [8, 7, 8, 6, 7, 5, 6, 5],
    },
    {
      id: "alerts",
      label: "Cảnh báo mở",
      value: 18,
      display: "18",
      growth: "+3 case vs hôm qua",
      growthUp: true,
      spark: [2, 3, 2, 4, 3, 5, 4, 6],
    },
    {
      id: "revenue",
      label: "Doanh thu MTD",
      value: 42.8,
      display: "₫42.8B",
      growth: "+6.4% vs kế hoạch",
      growthUp: true,
      spark: [5, 6, 6, 7, 8, 8, 9, 10],
    },
    {
      id: "stockout",
      label: "SKU stock-out",
      value: 37,
      display: "37",
      growth: "−5 SKU vs tuần trước",
      growthUp: false,
      spark: [10, 9, 8, 8, 7, 6, 5, 5],
    },
  ],
  charts: {
    revenue: buildRevenueChart("vi"),
    campaign: {
      labels: [
        "Tết herb",
        "Omega-3",
        "Immune+",
        "Sleep",
        "Detox",
        "Vitamin C",
        "Collagen",
        "Probiotic",
      ],
      values: [4.1, 2.6, 3.3, 2.2, 3.8, 3.1, 2.9, 4.5],
    },
  },
  customerCount: buildCustomerCountChart("vi"),
  demandMap: {
    summary: {
      regionsMonitored: 6,
      dangerCount: 1,
      warningCount: 2,
      stableCount: 3,
    },
    hotspots: [
      {
        id: "hn",
        city: "Hà Nội & Vùng KV",
        status: "danger",
        stockOutPct: 72,
        vendorScore: 61,
        demandTrend: "−4% WoW",
        top: "16.8%",
        left: "51.1%",
      },
      {
        id: "hp",
        city: "Hải Phòng",
        status: "warning",
        stockOutPct: 38,
        vendorScore: 70,
        demandTrend: "+1% WoW",
        top: "18%",
        left: "62.5%",
      },
      {
        id: "dn",
        city: "Đà Nẵng · Miền Trung",
        status: "warning",
        stockOutPct: 41,
        vendorScore: 74,
        demandTrend: "+6% WoW",
        top: "49.5%",
        left: "82.8%",
      },
      {
        id: "hcm",
        city: "TP. Hồ Chí Minh",
        status: "stable",
        stockOutPct: 22,
        vendorScore: 82,
        demandTrend: "+3% WoW",
        top: "83.8%",
        left: "61.8%",
      },
      {
        id: "ct",
        city: "Cần Thơ · ĐBSCL",
        status: "stable",
        stockOutPct: 19,
        vendorScore: 79,
        demandTrend: "+2% WoW",
        top: "89%",
        left: "50.4%",
      },
      {
        id: "nt",
        city: "Nha Trang",
        status: "stable",
        stockOutPct: 15,
        vendorScore: 85,
        demandTrend: "+5% WoW",
        top: "74.6%",
        left: "96.2%",
      },
    ],
  },
  purchaseTime: {
    labels: ["6h", "8h", "10h", "12h", "14h", "16h", "18h", "20h", "22h"],
    values: [4, 6, 9, 18, 11, 8, 16, 22, 6],
    peakIndices: [3, 7],
  },
  alerts: [
    {
      id: "1",
      priority: "P1",
      signal: "Stock-out SKU-4412 tại HN",
      source: "Inventory",
      decision: "Chuyển tồn từ HCM",
      owner: "Ops · Lan",
      sla: "2h",
      status: "danger",
      statusLabel: "Quá hạn",
    },
    {
      id: "2",
      priority: "P2",
      signal: "Vendor score < 65",
      source: "Vendor 360",
      decision: "Review hợp đồng",
      owner: "Proc · Minh",
      sla: "8h",
      status: "warning",
      statusLabel: "Đang xử lý",
    },
    {
      id: "3",
      priority: "P3",
      signal: "Campaign ROI < 2.0",
      source: "Marketing",
      decision: "Tối ưu audience",
      owner: "MKT · Hà",
      sla: "24h",
      status: "processing",
      statusLabel: "Theo dõi",
    },
    {
      id: "4",
      priority: "P2",
      signal: "Đơn OTC spike +18%",
      source: "Orders",
      decision: "Tăng forecast",
      owner: "Planning",
      sla: "12h",
      status: "success",
      statusLabel: "Đã xử lý",
    },
  ],
};
