import { buildCustomerCountChart } from "@/lib/customerCountChart";
import { buildRevenueChart } from "@/lib/dashboardRevenueChart";
import type { DashboardOverview } from "@/types/dashboard";

export const mockDashboardOverviewEn: DashboardOverview = {
  highlight: {
    c1t: "Monthly revenue",
    c1v: "42.8",
    c1s: "B",
    c2t: "Completed orders",
    c2v: "18,420",
    c3t: "Fill rate",
    c3v: "94.2%",
  },
  kpis: [
    {
      id: "vendors",
      label: "Active vendors",
      value: 1248,
      display: "1,248",
      growth: "+4.2% vs prior",
      growthUp: true,
      spark: [3, 5, 4, 7, 6, 9, 8, 10],
    },
    {
      id: "customers",
      label: "CRM customers",
      value: 248420,
      display: "248.4K",
      growth: "+2.8% vs prior",
      growthUp: true,
      spark: [4, 6, 5, 8, 7, 9, 10, 11],
    },
    {
      id: "signals",
      label: "Realtime signals",
      value: 324,
      display: "324",
      growth: "−1.1% vs prior",
      growthUp: false,
      spark: [8, 7, 8, 6, 7, 5, 6, 5],
    },
    {
      id: "alerts",
      label: "Open alerts",
      value: 18,
      display: "18",
      growth: "+3 vs yesterday",
      growthUp: true,
      spark: [2, 3, 2, 4, 3, 5, 4, 6],
    },
    {
      id: "revenue",
      label: "MTD revenue",
      value: 42.8,
      display: "$42.8B",
      growth: "+6.4% vs plan",
      growthUp: true,
      spark: [5, 6, 6, 7, 8, 8, 9, 10],
    },
    {
      id: "stockout",
      label: "Stock-out SKUs",
      value: 37,
      display: "37",
      growth: "−5 SKUs vs last week",
      growthUp: false,
      spark: [10, 9, 8, 8, 7, 6, 5, 5],
    },
  ],
  charts: {
    revenue: buildRevenueChart("en"),
    campaign: {
      labels: [
        "Tet herb",
        "Omega-3",
        "Immune+",
        "Sleep",
        "Detox",
        "Vitamin C",
        "Collagen",
        "Probiotic",
      ],
      values: [4.1, 2.6, 3.3, 2.2, 3.8, 3.1, 2.9, 4.5],
    },
  },
  customerCount: buildCustomerCountChart("en"),
  demandMap: {
    summary: {
      regionsMonitored: 6,
      dangerCount: 1,
      warningCount: 2,
      stableCount: 3,
    },
    hotspots: [
      {
        id: "hn",
        city: "Hanoi region",
        status: "danger",
        stockOutPct: 72,
        vendorScore: 61,
        demandTrend: "−4% WoW",
        top: "16.8%",
        left: "51.1%",
      },
      {
        id: "hp",
        city: "Hai Phong",
        status: "warning",
        stockOutPct: 38,
        vendorScore: 70,
        demandTrend: "+1% WoW",
        top: "18%",
        left: "62.5%",
      },
      {
        id: "dn",
        city: "Da Nang · Central",
        status: "warning",
        stockOutPct: 41,
        vendorScore: 74,
        demandTrend: "+6% WoW",
        top: "49.5%",
        left: "82.8%",
      },
      {
        id: "hcm",
        city: "Ho Chi Minh City",
        status: "stable",
        stockOutPct: 22,
        vendorScore: 82,
        demandTrend: "+3% WoW",
        top: "83.8%",
        left: "61.8%",
      },
      {
        id: "ct",
        city: "Can Tho · Mekong",
        status: "stable",
        stockOutPct: 19,
        vendorScore: 79,
        demandTrend: "+2% WoW",
        top: "89%",
        left: "50.4%",
      },
      {
        id: "nt",
        city: "Nha Trang",
        status: "stable",
        stockOutPct: 15,
        vendorScore: 85,
        demandTrend: "+5% WoW",
        top: "74.6%",
        left: "96.2%",
      },
    ],
  },
  purchaseTime: {
    labels: ["6am", "8am", "10am", "12pm", "2pm", "4pm", "6pm", "8pm", "10pm"],
    values: [4, 6, 9, 18, 11, 8, 16, 22, 6],
    peakIndices: [3, 7],
  },
  alerts: [
    {
      id: "1",
      priority: "P1",
      signal: "Stock-out SKU-4412 in Hanoi",
      source: "Inventory",
      decision: "Transfer stock from HCM",
      owner: "Ops · Lan",
      sla: "2h",
      status: "danger",
      statusLabel: "Overdue",
    },
    {
      id: "2",
      priority: "P2",
      signal: "Vendor score < 65",
      source: "Vendor 360",
      decision: "Contract review",
      owner: "Proc · Minh",
      sla: "8h",
      status: "warning",
      statusLabel: "In progress",
    },
    {
      id: "3",
      priority: "P3",
      signal: "Campaign ROI < 2.0",
      source: "Marketing",
      decision: "Tune audience",
      owner: "MKT · Ha",
      sla: "24h",
      status: "processing",
      statusLabel: "Watching",
    },
    {
      id: "4",
      priority: "P2",
      signal: "OTC orders spike +18%",
      source: "Orders",
      decision: "Raise forecast",
      owner: "Planning",
      sla: "12h",
      status: "success",
      statusLabel: "Resolved",
    },
  ],
};
