import { buildCustomerCountChart } from "@/lib/customerCountChart";
import { buildRevenueChart } from "@/lib/dashboardRevenueChart";
import type { DashboardOverview } from "@/types/dashboard";

export const mockDashboardOverviewZh: DashboardOverview = {
  highlight: {
    c1t: "月度营收",
    c1v: "42.8",
    c1s: " 十亿",
    c2t: "已完成订单",
    c2v: "18,420",
    c3t: "履约率",
    c3v: "94.2%",
  },
  kpis: [
    {
      id: "vendors",
      label: "活跃供应商",
      value: 1248,
      display: "1,248",
      growth: "较上期 +4.2%",
      growthUp: true,
      spark: [3, 5, 4, 7, 6, 9, 8, 10],
    },
    {
      id: "customers",
      label: "客户总数",
      value: 248420,
      display: "24.8万",
      growth: "较上期 +2.8%",
      growthUp: true,
      spark: [4, 6, 5, 8, 7, 9, 10, 11],
    },
    {
      id: "signals",
      label: "实时信号",
      value: 324,
      display: "324",
      growth: "较上期 −1.1%",
      growthUp: false,
      spark: [8, 7, 8, 6, 7, 5, 6, 5],
    },
    {
      id: "alerts",
      label: "未处理预警",
      value: 18,
      display: "18",
      growth: "较昨日 +3 条",
      growthUp: true,
      spark: [2, 3, 2, 4, 3, 5, 4, 6],
    },
    {
      id: "revenue",
      label: "月初至今营收",
      value: 42.8,
      display: "428亿",
      growth: "较计划 +6.4%",
      growthUp: true,
      spark: [5, 6, 6, 7, 8, 8, 9, 10],
    },
    {
      id: "stockout",
      label: "缺货商品数",
      value: 37,
      display: "37",
      growth: "较上周 −5 个",
      growthUp: false,
      spark: [10, 9, 8, 8, 7, 6, 5, 5],
    },
  ],
  charts: {
    revenue: buildRevenueChart("zh"),
    campaign: {
      labels: [
        "春节草本",
        "深海鱼油",
        "免疫增强",
        "助眠",
        "排毒",
        "维生素C",
        "胶原蛋白",
        "益生菌",
      ],
      values: [4.1, 2.6, 3.3, 2.2, 3.8, 3.1, 2.9, 4.5],
    },
  },
  customerCount: buildCustomerCountChart("zh"),
  demandMap: {
    summary: {
      regionsMonitored: 6,
      dangerCount: 1,
      warningCount: 2,
      stableCount: 3,
    },
    hotspots: [
      {
        id: "hn",
        city: "河内及周边",
        status: "danger",
        stockOutPct: 72,
        vendorScore: 61,
        demandTrend: "周环比 −4%",
        top: "16.8%",
        left: "51.1%",
      },
      {
        id: "hp",
        city: "海防",
        status: "warning",
        stockOutPct: 38,
        vendorScore: 70,
        demandTrend: "周环比 +1%",
        top: "18%",
        left: "62.5%",
      },
      {
        id: "dn",
        city: "岘港 · 中部",
        status: "warning",
        stockOutPct: 41,
        vendorScore: 74,
        demandTrend: "周环比 +6%",
        top: "49.5%",
        left: "82.8%",
      },
      {
        id: "hcm",
        city: "胡志明市",
        status: "stable",
        stockOutPct: 22,
        vendorScore: 82,
        demandTrend: "周环比 +3%",
        top: "83.8%",
        left: "61.8%",
      },
      {
        id: "ct",
        city: "芹苴 · 湄公河",
        status: "stable",
        stockOutPct: 19,
        vendorScore: 79,
        demandTrend: "周环比 +2%",
        top: "89%",
        left: "50.4%",
      },
      {
        id: "nt",
        city: "芽庄",
        status: "stable",
        stockOutPct: 15,
        vendorScore: 85,
        demandTrend: "周环比 +5%",
        top: "74.6%",
        left: "96.2%",
      },
    ],
  },
  purchaseTime: {
    labels: ["6时", "8时", "10时", "12时", "14时", "16时", "18时", "20时", "22时"],
    values: [4, 6, 9, 18, 11, 8, 16, 22, 6],
    peakIndices: [3, 7],
  },
  alerts: [
    {
      id: "1",
      priority: "P1",
      signal: "河内 商品4412 缺货",
      source: "库存",
      decision: "从胡志明市调拨",
      owner: "运营 · 阿兰",
      sla: "2小时",
      status: "danger",
      statusLabel: "已逾期",
    },
    {
      id: "2",
      priority: "P2",
      signal: "供应商评分 < 65",
      source: "供应商全景",
      decision: "合同复核",
      owner: "采购 · 阿敏",
      sla: "8小时",
      status: "warning",
      statusLabel: "处理中",
    },
    {
      id: "3",
      priority: "P3",
      signal: "活动回报率 < 2.0",
      source: "营销",
      decision: "优化受众",
      owner: "市场 · 阿霞",
      sla: "24小时",
      status: "processing",
      statusLabel: "观察中",
    },
    {
      id: "4",
      priority: "P2",
      signal: "非处方药订单激增 +18%",
      source: "订单",
      decision: "上调预测",
      owner: "计划部",
      sla: "12小时",
      status: "success",
      statusLabel: "已解决",
    },
  ],
};
