import { localizeInboundOrderRows } from "@/lib/inboundOrderData";
import { localizeProductInstances } from "@/lib/productInstances";
import type { ProductDetail, ProductListItem } from "@/types/product";
import { productMockVi } from "./product.mock";

const listZh: ProductListItem[] = [
  {
    productCode: "BSV-COV19",
    name: "越南新冠疫苗",
    category: "疫苗",
    brand: "Bông Sen Vàng",
    sellPrice: "185,000₫",
    importPrice: "142,000₫",
    status: "hot",
    statusLabel: "配送中",
    monthlyUnits: 186,
    monthlyRevenue: "3440万₫",
    growth: "+18.2%",
    growthUp: true,
    totalStock: 1000,
    locationCount: 16,
    avgDailyUnits: 6,
  },
  {
    productCode: "BSV-4412",
    name: "高级鱼油 60粒",
    category: "保健品",
    brand: "Bông Sen Vàng",
    sellPrice: "420,000₫",
    importPrice: "268,000₫",
    status: "hot",
    statusLabel: "热销",
    monthlyUnits: 842,
    monthlyRevenue: "3.53亿₫",
    growth: "+12.4%",
    growthUp: true,
    totalStock: 312,
    locationCount: 4,
    avgDailyUnits: 28,
  },
  {
    productCode: "BSV-2281",
    name: "维生素C 1000mg",
    category: "维生素",
    brand: "Bông Sen Vàng",
    sellPrice: "185,000₫",
    importPrice: "92,000₫",
    status: "stable",
    statusLabel: "稳定",
    monthlyUnits: 624,
    monthlyRevenue: "1.15亿₫",
    growth: "+3.1%",
    growthUp: true,
    totalStock: 198,
    locationCount: 4,
    avgDailyUnits: 21,
  },
  {
    productCode: "BSV-9033",
    name: "胶原蛋白肽",
    category: "美容",
    brand: "Bông Sen Vàng",
    sellPrice: "560,000₫",
    importPrice: "340,000₫",
    status: "slow",
    statusLabel: "滞销",
    monthlyUnits: 186,
    monthlyRevenue: "1.04亿₫",
    growth: "−8.2%",
    growthUp: false,
    totalStock: 94,
    locationCount: 3,
    avgDailyUnits: 6,
  },
  {
    productCode: "BSV-7710",
    name: "益生菌 30袋",
    category: "消化",
    brand: "Bông Sen Vàng",
    sellPrice: "295,000₫",
    importPrice: "168,000₫",
    status: "hot",
    statusLabel: "热销",
    monthlyUnits: 512,
    monthlyRevenue: "1.51亿₫",
    growth: "+9.6%",
    growthUp: true,
    totalStock: 228,
    locationCount: 4,
    avgDailyUnits: 17,
  },
  {
    productCode: "BSV-5520",
    name: "锌 + 维生素D3",
    category: "维生素",
    brand: "Bông Sen Vàng",
    sellPrice: "245,000₫",
    importPrice: "128,000₫",
    status: "stable",
    statusLabel: "稳定",
    monthlyUnits: 398,
    monthlyRevenue: "9700万₫",
    growth: "+1.8%",
    growthUp: true,
    totalStock: 156,
    locationCount: 4,
    avgDailyUnits: 13,
  },
  {
    productCode: "BSV-6108",
    name: "氨基葡萄糖 120粒",
    category: "保健品",
    brand: "Bông Sen Vàng",
    sellPrice: "380,000₫",
    importPrice: "210,000₫",
    status: "slow",
    statusLabel: "滞销",
    monthlyUnits: 142,
    monthlyRevenue: "5400万₫",
    growth: "−5.4%",
    growthUp: false,
    totalStock: 88,
    locationCount: 3,
    avgDailyUnits: 5,
  },
  {
    productCode: "BSV-3344",
    name: "胶原洁面乳",
    category: "美容",
    brand: "Bông Sen Vàng",
    sellPrice: "165,000₫",
    importPrice: "78,000₫",
    status: "new",
    statusLabel: "新品",
    monthlyUnits: 268,
    monthlyRevenue: "4400万₫",
    growth: "+24.0%",
    growthUp: true,
    totalStock: 120,
    locationCount: 2,
    avgDailyUnits: 9,
  },
  {
    productCode: "BSV-1199",
    name: "草本洗发水",
    category: "个护",
    brand: "Bông Sen Vàng",
    sellPrice: "125,000₫",
    importPrice: "62,000₫",
    status: "stable",
    statusLabel: "稳定",
    monthlyUnits: 456,
    monthlyRevenue: "5700万₫",
    growth: "+4.2%",
    growthUp: true,
    totalStock: 184,
    locationCount: 4,
    avgDailyUnits: 15,
  },
  {
    productCode: "BSV-8801",
    name: "甘氨酸镁",
    category: "保健品",
    brand: "Bông Sen Vàng",
    sellPrice: "320,000₫",
    importPrice: "175,000₫",
    status: "hot",
    statusLabel: "热销",
    monthlyUnits: 388,
    monthlyRevenue: "1.24亿₫",
    growth: "+15.1%",
    growthUp: true,
    totalStock: 142,
    locationCount: 3,
    avgDailyUnits: 13,
  },
  {
    productCode: "BSV-7022",
    name: "复合维生素B",
    category: "维生素",
    brand: "Bông Sen Vàng",
    sellPrice: "198,000₫",
    importPrice: "98,000₫",
    status: "out",
    statusLabel: "缺货",
    monthlyUnits: 0,
    monthlyRevenue: "0",
    growth: "—",
    growthUp: false,
    totalStock: 0,
    locationCount: 0,
    avgDailyUnits: 0,
  },
];

export const productMockZh = {
  list: () => listZh,
  detail: (code: string): ProductDetail => {
    const item = listZh.find((p) => p.productCode === code) ?? listZh[0];
    const base = productMockVi.detail(code);
    return {
      ...base,
      meta: {
        ...base.meta,
        productCode: item.productCode,
        name: item.name,
        category: item.category,
        brand: item.brand,
        sellPrice: item.sellPrice,
        importPrice: item.importPrice,
        status: item.status,
        statusLabel: item.statusLabel,
      },
      overview: {
        ...base.overview,
        kpis: base.overview.kpis.map((k, i) => ({
          ...k,
          label: ["总库存件数", "月营收", "月销量", "有货门店"][i] ?? k.label,
        })),
        channelMix: {
          labels: ["门店", "Zalo预订", "Grab", "其他"],
          values: base.overview.channelMix.values,
        },
      },
      instances: localizeProductInstances(base.instances, "zh"),
      inboundOrders: localizeInboundOrderRows(base.inboundOrders, "zh"),
    };
  },
  meta: (code: string) => productMockZh.detail(code).meta,
};
