import { localizeInboundOrderRows } from "@/lib/inboundOrderData";
import { localizeProductInstances } from "@/lib/productInstances";
import type { ProductDetail, ProductListItem } from "@/types/product";
import { productMockVi } from "./product.mock";

const listEn: ProductListItem[] = [
  {
    productCode: "BSV-COV19",
    name: "Covid Vietnam Vaccine",
    category: "Vaccine",
    brand: "Bông Sen Vàng",
    sellPrice: "₫185,000",
    importPrice: "₫142,000",
    status: "hot",
    statusLabel: "In distribution",
    monthlyUnits: 186,
    monthlyRevenue: "₫34.4M",
    growth: "+18.2%",
    growthUp: true,
    totalStock: 1000,
    locationCount: 16,
    avgDailyUnits: 6,
  },
  {
    productCode: "BSV-4412",
    name: "Omega-3 Premium 60ct",
    category: "Supplements",
    brand: "Bông Sen Vàng",
    sellPrice: "₫420,000",
    importPrice: "₫268,000",
    status: "hot",
    statusLabel: "Best seller",
    monthlyUnits: 842,
    monthlyRevenue: "₫353M",
    growth: "+12.4%",
    growthUp: true,
    totalStock: 312,
    locationCount: 4,
    avgDailyUnits: 28,
  },
  {
    productCode: "BSV-2281",
    name: "Vitamin C 1000mg",
    category: "Vitamins",
    brand: "Bông Sen Vàng",
    sellPrice: "₫185,000",
    importPrice: "₫92,000",
    status: "stable",
    statusLabel: "Stable",
    monthlyUnits: 624,
    monthlyRevenue: "₫115M",
    growth: "+3.1%",
    growthUp: true,
    totalStock: 198,
    locationCount: 4,
    avgDailyUnits: 21,
  },
  {
    productCode: "BSV-9033",
    name: "Collagen Peptide",
    category: "Beauty",
    brand: "Bông Sen Vàng",
    sellPrice: "₫560,000",
    importPrice: "₫340,000",
    status: "slow",
    statusLabel: "Slow moving",
    monthlyUnits: 186,
    monthlyRevenue: "₫104M",
    growth: "−8.2%",
    growthUp: false,
    totalStock: 94,
    locationCount: 3,
    avgDailyUnits: 6,
  },
  {
    productCode: "BSV-7710",
    name: "Probiotic 30s",
    category: "Digestive",
    brand: "Bông Sen Vàng",
    sellPrice: "₫295,000",
    importPrice: "₫168,000",
    status: "hot",
    statusLabel: "Best seller",
    monthlyUnits: 512,
    monthlyRevenue: "₫151M",
    growth: "+9.6%",
    growthUp: true,
    totalStock: 228,
    locationCount: 4,
    avgDailyUnits: 17,
  },
  {
    productCode: "BSV-5520",
    name: "Zinc + Vitamin D3",
    category: "Vitamins",
    brand: "Bông Sen Vàng",
    sellPrice: "₫245,000",
    importPrice: "₫128,000",
    status: "stable",
    statusLabel: "Stable",
    monthlyUnits: 398,
    monthlyRevenue: "₫97M",
    growth: "+1.8%",
    growthUp: true,
    totalStock: 156,
    locationCount: 4,
    avgDailyUnits: 13,
  },
  {
    productCode: "BSV-6108",
    name: "Glucosamine 120ct",
    category: "Supplements",
    brand: "Bông Sen Vàng",
    sellPrice: "₫380,000",
    importPrice: "₫210,000",
    status: "slow",
    statusLabel: "Slow moving",
    monthlyUnits: 142,
    monthlyRevenue: "₫54M",
    growth: "−5.4%",
    growthUp: false,
    totalStock: 88,
    locationCount: 3,
    avgDailyUnits: 5,
  },
  {
    productCode: "BSV-3344",
    name: "Collagen Face Wash",
    category: "Beauty",
    brand: "Bông Sen Vàng",
    sellPrice: "₫165,000",
    importPrice: "₫78,000",
    status: "new",
    statusLabel: "New",
    monthlyUnits: 268,
    monthlyRevenue: "₫44M",
    growth: "+24.0%",
    growthUp: true,
    totalStock: 120,
    locationCount: 2,
    avgDailyUnits: 9,
  },
  {
    productCode: "BSV-1199",
    name: "Herbal Shampoo",
    category: "Personal care",
    brand: "Bông Sen Vàng",
    sellPrice: "₫125,000",
    importPrice: "₫62,000",
    status: "stable",
    statusLabel: "Stable",
    monthlyUnits: 456,
    monthlyRevenue: "₫57M",
    growth: "+4.2%",
    growthUp: true,
    totalStock: 184,
    locationCount: 4,
    avgDailyUnits: 15,
  },
  {
    productCode: "BSV-8801",
    name: "Magnesium Glycinate",
    category: "Supplements",
    brand: "Bông Sen Vàng",
    sellPrice: "₫320,000",
    importPrice: "₫175,000",
    status: "hot",
    statusLabel: "Best seller",
    monthlyUnits: 388,
    monthlyRevenue: "₫124M",
    growth: "+15.1%",
    growthUp: true,
    totalStock: 142,
    locationCount: 3,
    avgDailyUnits: 13,
  },
  {
    productCode: "BSV-7022",
    name: "Vitamin B Complex",
    category: "Vitamins",
    brand: "Bông Sen Vàng",
    sellPrice: "₫198,000",
    importPrice: "₫98,000",
    status: "out",
    statusLabel: "Out of stock",
    monthlyUnits: 0,
    monthlyRevenue: "₫0",
    growth: "—",
    growthUp: false,
    totalStock: 0,
    locationCount: 0,
    avgDailyUnits: 0,
  },
];

export const productMockEn = {
  list: () => listEn,
  detail: (code: string): ProductDetail => {
    const item = listEn.find((p) => p.productCode === code) ?? listEn[0];
    const base = productMockVi.detail(code);
    return {
      ...base,
      meta: {
        ...base.meta,
        productCode: item.productCode,
        name: item.name,
        category: item.category,
        brand: item.brand,
        sellPrice: item.sellPrice,
        importPrice: item.importPrice,
        status: item.status,
        statusLabel: item.statusLabel,
      },
      overview: {
        ...base.overview,
        kpis: base.overview.kpis.map((k, i) => ({
          ...k,
          label: ["Total units in stock", "Monthly revenue", "Units sold (month)", "Locations stocking"][i] ?? k.label,
        })),
        channelMix: {
          labels: ["In-store", "Zalo order", "Grab", "Other"],
          values: base.overview.channelMix.values,
        },
      },
      instances: localizeProductInstances(base.instances, "en"),
      inboundOrders: localizeInboundOrderRows(base.inboundOrders, "en"),
    };
  },
  meta: (code: string) => productMockEn.detail(code).meta,
};
