import type { LocationStatus, LocationType } from "@/types/location";

export interface LocationSeed {
  id: string;
  code: string;
  trackingPrefix: string;
  nameVi: string;
  nameEn: string;
  nameZh: string;
  shortNameVi: string;
  cityVi: string;
  cityEn: string;
  cityZh: string;
  addressVi: string;
  addressEn: string;
  addressZh: string;
  type: LocationType;
  managerVi: string;
  managerEn: string;
  managerZh: string;
  staffCount: number;
  status: LocationStatus;
  monthlyRevenueVi: string;
  monthlyRevenueEn: string;
  monthlyRevenueZh: string;
  fillRatePct: number;
  openSince: string;
}

export const LOCATION_SEEDS: LocationSeed[] = [
  {
    id: "loc-hcm-1",
    code: "HCM-01",
    trackingPrefix: "TK-HCM01",
    nameVi: "Bông Sen Vàng · Quận 1",
    nameEn: "Golden Lotus · District 1",
    nameZh: "金莲花 · 第一郡",
    shortNameVi: "BSV Quận 1",
    cityVi: "TP. Hồ Chí Minh",
    cityEn: "Ho Chi Minh City",
    cityZh: "胡志明市",
    addressVi: "12 Nguyễn Huệ, Quận 1",
    addressEn: "12 Nguyen Hue, District 1",
    addressZh: "胡志明市第一郡阮惠街12号",
    type: "owned",
    managerVi: "Nguyễn Minh Anh",
    managerEn: "Minh Anh Nguyen",
    managerZh: "阮明英",
    staffCount: 18,
    status: "active",
    monthlyRevenueVi: "₫8.4 tỷ",
    monthlyRevenueEn: "₫8.4B",
    monthlyRevenueZh: "84亿₫",
    fillRatePct: 96,
    openSince: "03/2022",
  },
  {
    id: "loc-hcm-2",
    code: "HCM-02",
    trackingPrefix: "TK-HCM02",
    nameVi: "Bông Sen Vàng · Quận 3",
    nameEn: "Golden Lotus · District 3",
    nameZh: "金莲花 · 第三郡",
    shortNameVi: "BSV Quận 3",
    cityVi: "TP. Hồ Chí Minh",
    cityEn: "Ho Chi Minh City",
    cityZh: "胡志明市",
    addressVi: "45 Võ Văn Tần, Quận 3",
    addressEn: "45 Vo Van Tan, District 3",
    addressZh: "胡志明市第三郡武文担街45号",
    type: "owned",
    managerVi: "Lê Hoàng Yến",
    managerEn: "Hoang Yen Le",
    managerZh: "黎黄燕",
    staffCount: 16,
    status: "active",
    monthlyRevenueVi: "₫6.8 tỷ",
    monthlyRevenueEn: "₫6.8B",
    monthlyRevenueZh: "68亿₫",
    fillRatePct: 94,
    openSince: "07/2022",
  },
  {
    id: "loc-hcm-3",
    code: "HCM-03",
    trackingPrefix: "TK-HCM03",
    nameVi: "Bông Sen Vàng · Quận 7",
    nameEn: "Golden Lotus · District 7",
    nameZh: "金莲花 · 第七郡",
    shortNameVi: "BSV Quận 7",
    cityVi: "TP. Hồ Chí Minh",
    cityEn: "Ho Chi Minh City",
    cityZh: "胡志明市",
    addressVi: "88 Nguyễn Thị Thập, Quận 7",
    addressEn: "88 Nguyen Thi Thap, District 7",
    addressZh: "胡志明市第七郡阮氏添街88号",
    type: "franchise",
    managerVi: "Phan Quốc Huy",
    managerEn: "Quoc Huy Phan",
    managerZh: "潘国辉",
    staffCount: 14,
    status: "active",
    monthlyRevenueVi: "₫5.2 tỷ",
    monthlyRevenueEn: "₫5.2B",
    monthlyRevenueZh: "52亿₫",
    fillRatePct: 91,
    openSince: "02/2023",
  },
  {
    id: "loc-hcm-4",
    code: "HCM-04",
    trackingPrefix: "TK-HCM04",
    nameVi: "Bông Sen Vàng · Thủ Đức",
    nameEn: "Golden Lotus · Thu Duc",
    nameZh: "金莲花 · 守德",
    shortNameVi: "BSV Thủ Đức",
    cityVi: "TP. Hồ Chí Minh",
    cityEn: "Ho Chi Minh City",
    cityZh: "胡志明市",
    addressVi: "120 Võ Văn Ngân, Thủ Đức",
    addressEn: "120 Vo Van Ngan, Thu Duc",
    addressZh: "胡志明市守德范文银街120号",
    type: "franchise",
    managerVi: "Trương Bảo Ngọc",
    managerEn: "Bao Ngoc Truong",
    managerZh: "张宝玉",
    staffCount: 13,
    status: "active",
    monthlyRevenueVi: "₫4.6 tỷ",
    monthlyRevenueEn: "₫4.6B",
    monthlyRevenueZh: "46亿₫",
    fillRatePct: 89,
    openSince: "09/2023",
  },
  {
    id: "loc-hcm-5",
    code: "HCM-05",
    trackingPrefix: "TK-HCM05",
    nameVi: "Bông Sen Vàng · Bình Thạnh",
    nameEn: "Golden Lotus · Binh Thanh",
    nameZh: "金莲花 · 平盛",
    shortNameVi: "BSV Bình Thạnh",
    cityVi: "TP. Hồ Chí Minh",
    cityEn: "Ho Chi Minh City",
    cityZh: "胡志明市",
    addressVi: "25 Điện Biên Phủ, Bình Thạnh",
    addressEn: "25 Dien Bien Phu, Binh Thanh",
    addressZh: "胡志明市平盛奠边府街25号",
    type: "owned",
    managerVi: "Võ Thanh Tùng",
    managerEn: "Thanh Tung Vo",
    managerZh: "武清勇",
    staffCount: 15,
    status: "active",
    monthlyRevenueVi: "₫5.9 tỷ",
    monthlyRevenueEn: "₫5.9B",
    monthlyRevenueZh: "59亿₫",
    fillRatePct: 92,
    openSince: "11/2023",
  },
  {
    id: "loc-hn-1",
    code: "HN-01",
    trackingPrefix: "TK-HN01",
    nameVi: "Bông Sen Vàng · Hoàn Kiếm",
    nameEn: "Golden Lotus · Hoan Kiem",
    nameZh: "金莲花 · 还剑",
    shortNameVi: "BSV Hoàn Kiếm",
    cityVi: "Hà Nội",
    cityEn: "Hanoi",
    cityZh: "河内",
    addressVi: "45 Hàng Bài, Hoàn Kiếm",
    addressEn: "45 Hang Bai, Hoan Kiem",
    addressZh: "河内还剑郡行牌街45号",
    type: "franchise",
    managerVi: "Trần Quốc Bảo",
    managerEn: "Quoc Bao Tran",
    managerZh: "陈国宝",
    staffCount: 14,
    status: "active",
    monthlyRevenueVi: "₫6.1 tỷ",
    monthlyRevenueEn: "₫6.1B",
    monthlyRevenueZh: "61亿₫",
    fillRatePct: 91,
    openSince: "08/2023",
  },
  {
    id: "loc-hn-2",
    code: "HN-02",
    trackingPrefix: "TK-HN02",
    nameVi: "Bông Sen Vàng · Cầu Giấy",
    nameEn: "Golden Lotus · Cau Giay",
    nameZh: "金莲花 · 纸桥",
    shortNameVi: "BSV Cầu Giấy",
    cityVi: "Hà Nội",
    cityEn: "Hanoi",
    cityZh: "河内",
    addressVi: "12 Xuân Thủy, Cầu Giấy",
    addressEn: "12 Xuan Thuy, Cau Giay",
    addressZh: "河内纸桥郡春垂街12号",
    type: "owned",
    managerVi: "Đặng Thu Hà",
    managerEn: "Thu Ha Dang",
    managerZh: "邓秋河",
    staffCount: 16,
    status: "active",
    monthlyRevenueVi: "₫7.2 tỷ",
    monthlyRevenueEn: "₫7.2B",
    monthlyRevenueZh: "72亿₫",
    fillRatePct: 95,
    openSince: "04/2022",
  },
  {
    id: "loc-hn-3",
    code: "HN-03",
    trackingPrefix: "TK-HN03",
    nameVi: "Bông Sen Vàng · Long Biên",
    nameEn: "Golden Lotus · Long Bien",
    nameZh: "金莲花 · 龙编",
    shortNameVi: "BSV Long Biên",
    cityVi: "Hà Nội",
    cityEn: "Hanoi",
    cityZh: "河内",
    addressVi: "8 Ngọc Lâm, Long Biên",
    addressEn: "8 Ngoc Lam, Long Bien",
    addressZh: "河内龙编郡玉林街8号",
    type: "franchise",
    managerVi: "Nguyễn Hữu Phúc",
    managerEn: "Huu Phuc Nguyen",
    managerZh: "阮有福",
    staffCount: 11,
    status: "active",
    monthlyRevenueVi: "₫3.8 tỷ",
    monthlyRevenueEn: "₫3.8B",
    monthlyRevenueZh: "38亿₫",
    fillRatePct: 87,
    openSince: "05/2024",
  },
  {
    id: "loc-hn-4",
    code: "HN-04",
    trackingPrefix: "TK-HN04",
    nameVi: "Bông Sen Vàng · Đống Đa",
    nameEn: "Golden Lotus · Dong Da",
    nameZh: "金莲花 · 栋多",
    shortNameVi: "BSV Đống Đa",
    cityVi: "Hà Nội",
    cityEn: "Hanoi",
    cityZh: "河内",
    addressVi: "102 Tây Sơn, Đống Đa",
    addressEn: "102 Tay Son, Dong Da",
    addressZh: "河内栋多郡西山街102号",
    type: "owned",
    managerVi: "Hoàng Thị Lan",
    managerEn: "Thi Lan Hoang",
    managerZh: "黄氏兰",
    staffCount: 12,
    status: "paused",
    monthlyRevenueVi: "₫1.2 tỷ",
    monthlyRevenueEn: "₫1.2B",
    monthlyRevenueZh: "12亿₫",
    fillRatePct: 68,
    openSince: "01/2024",
  },
  {
    id: "loc-dn-1",
    code: "DN-01",
    trackingPrefix: "TK-DN01",
    nameVi: "Bông Sen Vàng · Hải Châu",
    nameEn: "Golden Lotus · Hai Chau",
    nameZh: "金莲花 · 海州",
    shortNameVi: "BSV Hải Châu",
    cityVi: "Đà Nẵng",
    cityEn: "Da Nang",
    cityZh: "岘港",
    addressVi: "88 Trần Phú, Hải Châu",
    addressEn: "88 Tran Phu, Hai Chau",
    addressZh: "岘港海州郡陈富街88号",
    type: "franchise",
    managerVi: "Lê Thị Hương",
    managerEn: "Huong Le",
    managerZh: "黎氏香",
    staffCount: 11,
    status: "active",
    monthlyRevenueVi: "₫3.2 tỷ",
    monthlyRevenueEn: "₫3.2B",
    monthlyRevenueZh: "32亿₫",
    fillRatePct: 88,
    openSince: "01/2024",
  },
  {
    id: "loc-dn-2",
    code: "DN-02",
    trackingPrefix: "TK-DN02",
    nameVi: "Bông Sen Vàng · Sơn Trà",
    nameEn: "Golden Lotus · Son Tra",
    nameZh: "金莲花 · 山茶",
    shortNameVi: "BSV Sơn Trà",
    cityVi: "Đà Nẵng",
    cityEn: "Da Nang",
    cityZh: "岘港",
    addressVi: "15 Võ Nguyên Giáp, Sơn Trà",
    addressEn: "15 Vo Nguyen Giap, Son Tra",
    addressZh: "岘港山茶郡武元甲街15号",
    type: "franchise",
    managerVi: "Ngô Văn Khánh",
    managerEn: "Van Khanh Ngo",
    managerZh: "吴文庆",
    staffCount: 10,
    status: "active",
    monthlyRevenueVi: "₫2.8 tỷ",
    monthlyRevenueEn: "₫2.8B",
    monthlyRevenueZh: "28亿₫",
    fillRatePct: 86,
    openSince: "06/2024",
  },
  {
    id: "loc-hp-1",
    code: "HP-01",
    trackingPrefix: "TK-HP01",
    nameVi: "Bông Sen Vàng · Lê Chân",
    nameEn: "Golden Lotus · Le Chan",
    nameZh: "金莲花 · 黎真",
    shortNameVi: "BSV Lê Chân",
    cityVi: "Hải Phòng",
    cityEn: "Hai Phong",
    cityZh: "海防",
    addressVi: "220 Lạch Tray, Lê Chân",
    addressEn: "220 Lach Tray, Le Chan",
    addressZh: "海防黎真郡沥拆街220号",
    type: "franchise",
    managerVi: "Bùi Minh Đức",
    managerEn: "Minh Duc Bui",
    managerZh: "裴明德",
    staffCount: 10,
    status: "active",
    monthlyRevenueVi: "₫2.4 tỷ",
    monthlyRevenueEn: "₫2.4B",
    monthlyRevenueZh: "24亿₫",
    fillRatePct: 84,
    openSince: "03/2024",
  },
  {
    id: "loc-ct-1",
    code: "CT-01",
    trackingPrefix: "TK-CT01",
    nameVi: "Bông Sen Vàng · Ninh Kiều",
    nameEn: "Golden Lotus · Ninh Kieu",
    nameZh: "金莲花 · 宁桥",
    shortNameVi: "BSV Ninh Kiều",
    cityVi: "Cần Thơ",
    cityEn: "Can Tho",
    cityZh: "芹苴",
    addressVi: "5 Nguyễn Trãi, Ninh Kiều",
    addressEn: "5 Nguyen Trai, Ninh Kieu",
    addressZh: "芹苴宁桥郡阮截街5号",
    type: "owned",
    managerVi: "Phạm Văn Đức",
    managerEn: "Duc Pham",
    managerZh: "范文德",
    staffCount: 9,
    status: "setup",
    monthlyRevenueVi: "₫0.9 tỷ",
    monthlyRevenueEn: "₫0.9B",
    monthlyRevenueZh: "9亿₫",
    fillRatePct: 72,
    openSince: "11/2025",
  },
  {
    id: "loc-ct-2",
    code: "CT-02",
    trackingPrefix: "TK-CT02",
    nameVi: "Bông Sen Vàng · Cái Răng",
    nameEn: "Golden Lotus · Cai Rang",
    nameZh: "金莲花 · 丐𦨭",
    shortNameVi: "BSV Cái Răng",
    cityVi: "Cần Thơ",
    cityEn: "Can Tho",
    cityZh: "芹苴",
    addressVi: "48 Lê Văn Việt, Cái Răng",
    addressEn: "48 Le Van Viet, Cai Rang",
    addressZh: "芹苴丐𦨭郡黎文越街48号",
    type: "franchise",
    managerVi: "Lý Thanh Nhàn",
    managerEn: "Thanh Nhan Ly",
    managerZh: "李清彦",
    staffCount: 8,
    status: "active",
    monthlyRevenueVi: "₫1.6 tỷ",
    monthlyRevenueEn: "₫1.6B",
    monthlyRevenueZh: "16亿₫",
    fillRatePct: 79,
    openSince: "02/2025",
  },
  {
    id: "loc-bd-1",
    code: "BD-01",
    trackingPrefix: "TK-BD01",
    nameVi: "Bông Sen Vàng · Thuận An",
    nameEn: "Golden Lotus · Thuan An",
    nameZh: "金莲花 · 顺安",
    shortNameVi: "BSV Thuận An",
    cityVi: "Bình Dương",
    cityEn: "Binh Duong",
    cityZh: "平阳",
    addressVi: "30 Đại lộ Bình Dương, Thuận An",
    addressEn: "30 Binh Duong Blvd, Thuan An",
    addressZh: "平阳顺安平阳大道30号",
    type: "franchise",
    managerVi: "Đinh Quang Minh",
    managerEn: "Quang Minh Dinh",
    managerZh: "丁光明",
    staffCount: 12,
    status: "active",
    monthlyRevenueVi: "₫3.5 tỷ",
    monthlyRevenueEn: "₫3.5B",
    monthlyRevenueZh: "35亿₫",
    fillRatePct: 90,
    openSince: "10/2023",
  },
  {
    id: "loc-nt-1",
    code: "NT-01",
    trackingPrefix: "TK-NT01",
    nameVi: "Bông Sen Vàng · Nha Trang",
    nameEn: "Golden Lotus · Nha Trang",
    nameZh: "金莲花 · 芽庄",
    shortNameVi: "BSV Nha Trang",
    cityVi: "Khánh Hòa",
    cityEn: "Khanh Hoa",
    cityZh: "庆和",
    addressVi: "22 Trần Phú, Nha Trang",
    addressEn: "22 Tran Phu, Nha Trang",
    addressZh: "芽庄陈富街22号",
    type: "franchise",
    managerVi: "Võ Ngọc Hân",
    managerEn: "Ngoc Han Vo",
    managerZh: "武玉汗",
    staffCount: 11,
    status: "active",
    monthlyRevenueVi: "₫2.9 tỷ",
    monthlyRevenueEn: "₫2.9B",
    monthlyRevenueZh: "29亿₫",
    fillRatePct: 85,
    openSince: "04/2024",
  },
  {
    id: "loc-hue-1",
    code: "HUE-01",
    trackingPrefix: "TK-HUE01",
    nameVi: "Bông Sen Vàng · Huế",
    nameEn: "Golden Lotus · Hue",
    nameZh: "金莲花 · 顺化",
    shortNameVi: "BSV Huế",
    cityVi: "Thừa Thiên Huế",
    cityEn: "Thua Thien Hue",
    cityZh: "承天顺化",
    addressVi: "8 Lê Lợi, TP. Huế",
    addressEn: "8 Le Loi, Hue City",
    addressZh: "顺化黎利街8号",
    type: "owned",
    managerVi: "Nguyễn Phước Thịnh",
    managerEn: "Phuoc Thinh Nguyen",
    managerZh: "阮福盛",
    staffCount: 9,
    status: "active",
    monthlyRevenueVi: "₫2.1 tỷ",
    monthlyRevenueEn: "₫2.1B",
    monthlyRevenueZh: "21亿₫",
    fillRatePct: 82,
    openSince: "08/2024",
  },
  {
    id: "loc-vt-1",
    code: "VT-01",
    trackingPrefix: "TK-VT01",
    nameVi: "Bông Sen Vàng · Vũng Tàu",
    nameEn: "Golden Lotus · Vung Tau",
    nameZh: "金莲花 · 头顿",
    shortNameVi: "BSV Vũng Tàu",
    cityVi: "Bà Rịa – Vũng Tàu",
    cityEn: "Ba Ria – Vung Tau",
    cityZh: "巴地头顿",
    addressVi: "6 Trần Phú, Vũng Tàu",
    addressEn: "6 Tran Phu, Vung Tau",
    addressZh: "头顿陈富街6号",
    type: "franchise",
    managerVi: "Trần Mỹ Linh",
    managerEn: "My Linh Tran",
    managerZh: "陈美玲",
    staffCount: 8,
    status: "paused",
    monthlyRevenueVi: "₫0.8 tỷ",
    monthlyRevenueEn: "₫0.8B",
    monthlyRevenueZh: "8亿₫",
    fillRatePct: 65,
    openSince: "12/2024",
  },
];

export const LOCATION_IDS = LOCATION_SEEDS.map((s) => s.id);

export function getLocationSeed(id: string): LocationSeed {
  return LOCATION_SEEDS.find((s) => s.id === id) ?? LOCATION_SEEDS[0];
}

export function locationIndex(id: string): number {
  const i = LOCATION_SEEDS.findIndex((s) => s.id === id);
  return i >= 0 ? i : 0;
}
