import type { HeritageModuleData } from "@/types/heritage";

export const heritageMockEn: HeritageModuleData = {
  tradeMarketing: {
    merchandiseDisplay: [
      {
        id: "tm-md-1",
        name: "TCM heritage display corner",
        status: "Active",
        metric: "Zone revenue +22%",
        period: "Q1/2026",
        owner: "VM & merchandising",
      },
      {
        id: "tm-md-2",
        name: "Shelf A — medicinal tea & herbs",
        status: "Active",
        metric: "+2 facings · 28 stores",
        period: "Mar/2026",
        owner: "VM team",
      },
      {
        id: "tm-md-3",
        name: "Main shelf standee — Thuong Son Tra",
        status: "Completed",
        metric: "96% compliance",
        period: "Q4/2025",
        owner: "Trade ops",
      },
      {
        id: "tm-md-4",
        name: "New price board & shelf talkers",
        status: "Planned",
        metric: "36/36 stores updated",
        period: "01 Apr/2026",
        owner: "Trade ops",
      },
      {
        id: "tm-md-5",
        name: "Yogi Food display audit",
        status: "Monitoring",
        metric: "3 stores need facing fix",
        period: "Week 13/2026",
        owner: "South area supervisor",
      },
    ],
    salesTraining: [
      {
        id: "tm-st-1",
        name: "POS training — medicinal tea upsell script",
        status: "Active",
        metric: "Audit score 88/100",
        period: "Q2/2026",
        owner: "Store training",
      },
      {
        id: "tm-st-2",
        name: "TCM OTC workshop for counter staff",
        status: "Active",
        metric: "124 staff completed",
        period: "Mar/2026",
        owner: "Product training",
      },
      {
        id: "tm-st-3",
        name: "E-learning — Yogi Food nutritional snacks",
        status: "Planned",
        metric: "Target 200 staff",
        period: "Q2/2026",
        owner: "Yogi Food trade",
      },
      {
        id: "tm-st-4",
        name: "Weekend shift skills check",
        status: "Monitoring",
        metric: "4 stores below 75",
        period: "Week 12/2026",
        owner: "North area supervisor",
      },
      {
        id: "tm-st-5",
        name: "New hire onboarding — greeting script",
        status: "Completed",
        metric: "42 staff · 95% pass",
        period: "Q2/2026",
        owner: "HR & training",
      },
    ],
    customerCare: [
      {
        id: "tm-cc-1",
        name: "Gold-tier customer activation",
        status: "Active",
        metric: "Repeat purchase +9%",
        period: "Ongoing",
        owner: "CRM & trade",
      },
      {
        id: "tm-cc-2",
        name: "7-day post-purchase care program",
        status: "Active",
        metric: "CSAT 4.6/5",
        period: "Mar/2026",
        owner: "Customer care",
      },
      {
        id: "tm-cc-3",
        name: "In-store CS hotline — complaint script",
        status: "Completed",
        metric: "Handle time −18%",
        period: "Q1/2026",
        owner: "Store operations",
      },
      {
        id: "tm-cc-4",
        name: "VIP birthday gift program",
        status: "Planned",
        metric: "2.1K target customers",
        period: "Q2/2026",
        owner: "CRM",
      },
      {
        id: "tm-cc-5",
        name: "Medicinal tea sampling feedback booth",
        status: "Monitoring",
        metric: "NPS 68",
        period: "Weeks 12–16/2026",
        owner: "Field activation",
      },
    ],
    salesPolicy: [
      {
        id: "tm-sp-1",
        name: "15% off TCM ETC — weekends",
        status: "Active",
        metric: "Revenue lift 11%",
        period: "Mar/2026",
        owner: "Pricing & trade",
      },
      {
        id: "tm-sp-2",
        name: "Buy 2 get 1 medicinal tea",
        status: "Active",
        metric: "2.4 SKU/basket attach",
        period: "Mar/2026",
        owner: "Trade — Central",
      },
      {
        id: "tm-sp-3",
        name: "TCM distributor discount policy",
        status: "Active",
        metric: "124 distributors",
        period: "2026",
        owner: "Professional channel",
      },
      {
        id: "tm-sp-4",
        name: "Return allowance — Thuong Son Tra",
        status: "Monitoring",
        metric: "Return rate 1.2%",
        period: "Ongoing",
        owner: "Trade policy",
      },
      {
        id: "tm-sp-5",
        name: "Listed price update — Q2 rollout",
        status: "Planned",
        metric: "36 stores network-wide",
        period: "01 Apr/2026",
        owner: "Pricing",
      },
    ],
    seasonalCampaigns: [
      {
        id: "tm-sc-1",
        name: "Lunar New Year 2026 POS",
        status: "Completed",
        metric: "ROI 3.8×",
        period: "Q1/2026",
        owner: "Trade — North region",
      },
      {
        id: "tm-sc-2",
        name: "Herbal sampling at counter",
        status: "Active",
        metric: "Conversion 18%",
        period: "Weeks 12–16/2026",
        owner: "Field activation",
      },
      {
        id: "tm-sc-3",
        name: "4-hour flash sale — Hanoi DC",
        status: "Completed",
        metric: "87% POS stock sold",
        period: "15 Feb/2026",
        owner: "Warehouse & trade HN",
      },
      {
        id: "tm-sc-4",
        name: "Tet gift — mini medicinal tea set",
        status: "Completed",
        metric: "Promo NPS 72",
        period: "Q1/2026",
        owner: "Brand activation",
      },
      {
        id: "tm-sc-5",
        name: "Summer campaign — Coffee & fruit",
        status: "Planned",
        metric: "Budget ₫240M",
        period: "May–Jul/2026",
        owner: "Central trade marketing",
      },
    ],
    newStoreOpening: [
      {
        id: "tm-no-1",
        name: "Da Nang 02 store grand opening",
        status: "Active",
        metric: "Week 1 revenue ₫186M",
        period: "Mar/2026",
        owner: "Network expansion",
      },
      {
        id: "tm-no-2",
        name: "Opening-week POS checklist rollout",
        status: "Active",
        metric: "94% completion",
        period: "Week 12/2026",
        owner: "Central area supervisor",
      },
      {
        id: "tm-no-3",
        name: "New-store display kit — 12 SKUs",
        status: "Planned",
        metric: "42 kits ready",
        period: "Q2/2026",
        owner: "VM & merchandising",
      },
      {
        id: "tm-no-4",
        name: "On-site opening training — 3 days",
        status: "Planned",
        metric: "18 staff/cohort",
        period: "Apr/2026",
        owner: "Store training",
      },
      {
        id: "tm-no-5",
        name: "Thuong Son Tra flagship grand opening",
        status: "Monitoring",
        metric: "Reach 3.2K visitors/day",
        period: "15 May/2026",
        owner: "Thuong Son Tra trade",
      },
    ],
  },
  insights: {
    risks: [
      {
        id: "in-r-1",
        name: "Slow stock GLH-120 — South",
        status: "High",
        metric: "Stock > 45 days",
        period: "Updated today",
        owner: "Warehouse & supply",
      },
      {
        id: "in-r-2",
        name: "Competitor pricing in Da Nang",
        status: "Medium",
        metric: "Shelf price −8%",
        period: "Week 11/2026",
        owner: "Trade intelligence",
      },
      {
        id: "in-r-3",
        name: "Weekend shift understaffing",
        status: "High",
        metric: "4 stores flagged",
        period: "Next weekend",
        owner: "Store operations",
      },
      {
        id: "in-r-4",
        name: "POS promotion execution gap",
        status: "Monitoring",
        metric: "3% wrong price orders",
        period: "Mar/2026",
        owner: "Internal audit",
      },
      {
        id: "in-r-5",
        name: "GLH-DETOX-B stockout risk",
        status: "Medium",
        metric: "9 days cover",
        period: "14-day forecast",
        owner: "Demand planning",
      },
    ],
    opportunities: [
      {
        id: "in-o-1",
        name: "Cross-sell detox + shampoo combo",
        status: "High priority",
        metric: "Potential +₫320M/mo",
        period: "Q2/2026",
        owner: "Category & trade",
      },
      {
        id: "in-o-2",
        name: "Gold customers post-Tet repurchase",
        status: "In progress",
        metric: "12K target customers",
        period: "Mar–Apr/2026",
        owner: "CRM",
      },
      {
        id: "in-o-3",
        name: "Expand main shelf facing in HCMC",
        status: "New proposal",
        metric: "Expected lift +15%",
        period: "Q2/2026",
        owner: "VM",
      },
      {
        id: "in-o-4",
        name: "Order online — pickup in store",
        status: "In progress",
        metric: "Share 8% → 12%",
        period: "6 months",
        owner: "Omnichannel",
      },
      {
        id: "in-o-5",
        name: "TCM hospital sampling partnership",
        status: "New proposal",
        metric: "Reach 2.1K customers/mo",
        period: "Q3/2026",
        owner: "Partnership",
      },
    ],
    forecasts: [
      {
        id: "in-f-1",
        name: "Network revenue Q2",
        status: "Forecast",
        metric: "+12% vs Q1",
        period: "Q2/2026",
        owner: "FP&A",
      },
      {
        id: "in-f-2",
        name: "GLH-DETOX-B demand",
        status: "Forecast",
        metric: "+18% volume",
        period: "Apr–Jun/2026",
        owner: "Demand planning",
      },
      {
        id: "in-f-3",
        name: "Optimal inventory June",
        status: "Model",
        metric: "DSO 32 days",
        period: "Jun/2026",
        owner: "Supply chain",
      },
      {
        id: "in-f-4",
        name: "Trade spend efficiency",
        status: "Forecast",
        metric: "Avg ROI 3.1×",
        period: "Q2/2026",
        owner: "Trade finance",
      },
      {
        id: "in-f-5",
        name: "Weekend footfall",
        status: "Forecast",
        metric: "+6% footfall",
        period: "Apr–May/2026",
        owner: "Ops analytics",
      },
    ],
    recommendations: [
      {
        id: "in-rec-1",
        name: "Increase GLH-4412 facing at TOP 8 stores",
        status: "Recommended",
        metric: "Priority 1",
        period: "Within 2 weeks",
        owner: "Trade steering",
      },
      {
        id: "in-rec-2",
        name: "Adjust promos in Da Nang",
        status: "Recommended",
        metric: "Shelf price −5%",
        period: "Week 13/2026",
        owner: "Pricing",
      },
      {
        id: "in-rec-3",
        name: "Retrain detox upsell script",
        status: "Recommended",
        metric: "6 low-score stores",
        period: "Apr/2026",
        owner: "Training",
      },
      {
        id: "in-rec-4",
        name: "Transfer GLH-120 stock North → South",
        status: "Recommended",
        metric: "Slow stock −20%",
        period: "Mar/2026",
        owner: "Central warehouse",
      },
      {
        id: "in-rec-5",
        name: "Increase digital coupon budget",
        status: "Under review",
        metric: "ROI > 3×",
        period: "Q2/2026",
        owner: "Marketing mix",
      },
    ],
  },
};
