import type { HeritageModuleData } from "@/types/heritage";

export const heritageMockVi: HeritageModuleData = {
  tradeMarketing: {
    merchandiseDisplay: [
      {
        id: "tm-md-1",
        name: "Góc trưng bày di sản YHCT",
        status: "Đang chạy",
        metric: "Doanh thu khu vực +22%",
        period: "Q1/2026",
        owner: "VM & Merchandising",
      },
      {
        id: "tm-md-2",
        name: "Merchandising kệ A — Trà dược & Dược liệu",
        status: "Đang chạy",
        metric: "Facing +2 mặt · 28 CH",
        period: "Tháng 3/2026",
        owner: "VM team",
      },
      {
        id: "tm-md-3",
        name: "Standee kệ chính — Thượng Sơn Trà",
        status: "Hoàn tất",
        metric: "Tuân thủ 96%",
        period: "Q4/2025",
        owner: "Trade ops",
      },
      {
        id: "tm-md-4",
        name: "Bảng giá & shelf talker mới",
        status: "Kế hoạch",
        metric: "36/36 CH cập nhật",
        period: "01/04/2026",
        owner: "Trade ops",
      },
      {
        id: "tm-md-5",
        name: "Audit trưng bày Yogi Food",
        status: "Theo dõi",
        metric: "3 CH cần chỉnh facing",
        period: "Tuần 13/2026",
        owner: "Giám sát vùng Nam",
      },
    ],
    salesTraining: [
      {
        id: "tm-st-1",
        name: "Đào tạo POS — script bán kèm Trà dược",
        status: "Đang chạy",
        metric: "Điểm kiểm 88/100",
        period: "T3/2026",
        owner: "Đào tạo cửa hàng",
      },
      {
        id: "tm-st-2",
        name: "Workshop Thuốc YHCT OTC cho CV quầy",
        status: "Đang chạy",
        metric: "124 NV hoàn thành",
        period: "Tháng 3/2026",
        owner: "Đào tạo sản phẩm",
      },
      {
        id: "tm-st-3",
        name: "E-learning Snacks dinh dưỡng — Yogi Food",
        status: "Kế hoạch",
        metric: "Mục tiêu 200 NV",
        period: "Q2/2026",
        owner: "Yogi Food trade",
      },
      {
        id: "tm-st-4",
        name: "Kiểm tra nghiệp vụ ca cuối tuần",
        status: "Theo dõi",
        metric: "4 CH điểm dưới 75",
        period: "Tuần 12/2026",
        owner: "Giám sát vùng Bắc",
      },
      {
        id: "tm-st-5",
        name: "Onboarding nhân viên mới — kịch bản chào hàng",
        status: "Hoàn tất",
        metric: "42 NV · pass 95%",
        period: "T2/2026",
        owner: "HR & Đào tạo",
      },
    ],
    customerCare: [
      {
        id: "tm-cc-1",
        name: "Kích hoạt khách hàng vàng",
        status: "Đang chạy",
        metric: "Tái mua +9%",
        period: "Liên tục",
        owner: "CRM & Trade",
      },
      {
        id: "tm-cc-2",
        name: "Chương trình chăm sóc sau mua 7 ngày",
        status: "Đang chạy",
        metric: "CSAT 4.6/5",
        period: "Tháng 3/2026",
        owner: "Chăm sóc KH",
      },
      {
        id: "tm-cc-3",
        name: "Hotline CSKH tại quầy — script xử lý khiếu nại",
        status: "Hoàn tất",
        metric: "Thời gian xử lý −18%",
        period: "Q1/2026",
        owner: "Vận hành CH",
      },
      {
        id: "tm-cc-4",
        name: "Quà tặng sinh nhật khách VIP",
        status: "Kế hoạch",
        metric: "2.1K khách mục tiêu",
        period: "Q2/2026",
        owner: "CRM",
      },
      {
        id: "tm-cc-5",
        name: "Feedback booth sampling Trà dược",
        status: "Theo dõi",
        metric: "NPS 68",
        period: "Tuần 12–16/2026",
        owner: "Field activation",
      },
    ],
    salesPolicy: [
      {
        id: "tm-sp-1",
        name: "Giảm 15% Thuốc YHCT ETC — cuối tuần",
        status: "Đang chạy",
        metric: "Lift doanh thu 11%",
        period: "T3/2026",
        owner: "Pricing & Trade",
      },
      {
        id: "tm-sp-2",
        name: "Mua 2 tặng 1 Trà dược",
        status: "Đang chạy",
        metric: "Bán kèm 2.4 SKU/đơn",
        period: "Tháng 3/2026",
        owner: "Trade — Miền Trung",
      },
      {
        id: "tm-sp-3",
        name: "Chính sách chiết khấu đại lý YHCT",
        status: "Đang chạy",
        metric: "124 đại lý áp dụng",
        period: "2026",
        owner: "Kênh chuyên",
      },
      {
        id: "tm-sp-4",
        name: "Hạn mức trả hàng — Thượng Sơn Trà",
        status: "Theo dõi",
        metric: "Tỷ lệ trả 1.2%",
        period: "Liên tục",
        owner: "Trade policy",
      },
      {
        id: "tm-sp-5",
        name: "Bảng giá niêm yết — cập nhật T3",
        status: "Kế hoạch",
        metric: "Toàn mạng 36 CH",
        period: "01/04/2026",
        owner: "Pricing",
      },
    ],
    seasonalCampaigns: [
      {
        id: "tm-sc-1",
        name: "POS Tết Nguyên Đán 2026",
        status: "Hoàn tất",
        metric: "ROI 3.8×",
        period: "Q1/2026",
        owner: "Nhóm Trade — Miền Bắc",
      },
      {
        id: "tm-sc-2",
        name: "Sampling thảo dược tại quầy",
        status: "Đang chạy",
        metric: "Chuyển đổi 18%",
        period: "Tuần 12–16/2026",
        owner: "Field activation",
      },
      {
        id: "tm-sc-3",
        name: "Flash sale 4h — kho Hà Nội",
        status: "Hoàn tất",
        metric: "Hết 87% tồn POS",
        period: "15/02/2026",
        owner: "Kho & Trade HN",
      },
      {
        id: "tm-sc-4",
        name: "Quà tặng Tết — set Trà dược mini",
        status: "Hoàn tất",
        metric: "NPS khuyến mãi 72",
        period: "T1/2026",
        owner: "Brand activation",
      },
      {
        id: "tm-sc-5",
        name: "Chiến dịch hè — Cafe & Trái cây",
        status: "Kế hoạch",
        metric: "Ngân sách ₫240M",
        period: "T5–T7/2026",
        owner: "Trade Marketing trung tâm",
      },
    ],
    newStoreOpening: [
      {
        id: "tm-no-1",
        name: "Khai trương CH Đà Nẵng 02",
        status: "Đang chạy",
        metric: "Doanh thu tuần 1: ₫186M",
        period: "Tháng 3/2026",
        owner: "Mở rộng mạng lưới",
      },
      {
        id: "tm-no-2",
        name: "Rollout checklist POS — tuần khai trương",
        status: "Đang chạy",
        metric: "Hoàn thành 94%",
        period: "Tuần 12/2026",
        owner: "Giám sát vùng Trung",
      },
      {
        id: "tm-no-3",
        name: "Bộ kit trưng bày mở mới — 12 SKU",
        status: "Kế hoạch",
        metric: "42 bộ sẵn sàng",
        period: "Q2/2026",
        owner: "VM & Merchandising",
      },
      {
        id: "tm-no-4",
        name: "Đào tạo khai trương — 3 ngày tại chỗ",
        status: "Kế hoạch",
        metric: "18 NV/đợt",
        period: "Tháng 4/2026",
        owner: "Đào tạo cửa hàng",
      },
      {
        id: "tm-no-5",
        name: "Grand opening Thượng Sơn Trà — flagship",
        status: "Theo dõi",
        metric: "Reach 3.2K khách/ngày",
        period: "15/05/2026",
        owner: "Thượng Sơn Trà trade",
      },
    ],
  },
  insights: {
    risks: [
      {
        id: "in-r-1",
        name: "Tồn chậm GLH-120 — khu vực Nam",
        status: "Cao",
        metric: "Tồn > 45 ngày",
        period: "Cập nhật hôm nay",
        owner: "Kho & Supply",
      },
      {
        id: "in-r-2",
        name: "Cạnh tranh giá đối thủ tại Đà Nẵng",
        status: "Trung bình",
        metric: "Chênh −8% giá kệ",
        period: "Tuần 11/2026",
        owner: "Trade intelligence",
      },
      {
        id: "in-r-3",
        name: "Thiếu nhân sự ca cuối tuần",
        status: "Cao",
        metric: "4 CH báo thiếu",
        period: "Cuối tuần tới",
        owner: "Vận hành CH",
      },
      {
        id: "in-r-4",
        name: "Lệch thực thi khuyến mãi POS",
        status: "Theo dõi",
        metric: "3% đơn sai giá",
        period: "Tháng 3/2026",
        owner: "Audit nội bộ",
      },
      {
        id: "in-r-5",
        name: "Rủi ro hết hàng GLH-DETOX-B",
        status: "Trung bình",
        metric: "Cover 9 ngày",
        period: "Dự báo 14 ngày",
        owner: "Demand planning",
      },
    ],
    opportunities: [
      {
        id: "in-o-1",
        name: "Cross-sell combo detox + gội",
        status: "Ưu tiên cao",
        metric: "Tiềm năng +₫320M/th",
        period: "Q2/2026",
        owner: "Category & Trade",
      },
      {
        id: "in-o-2",
        name: "Khách vàng tái mua sau Tết",
        status: "Đang khai thác",
        metric: "12K khách mục tiêu",
        period: "Tháng 3–4/2026",
        owner: "CRM",
      },
      {
        id: "in-o-3",
        name: "Mở rộng facing kệ chính HCM",
        status: "Đề xuất mới",
        metric: "Lift +15% dự kiến",
        period: "Q2/2026",
        owner: "VM",
      },
      {
        id: "in-o-4",
        name: "Kênh online đặt — lấy tại CH",
        status: "Đang khai thác",
        metric: "Tỷ trọng 8% → 12%",
        period: "6 tháng",
        owner: "Omnichannel",
      },
      {
        id: "in-o-5",
        name: "Hợp tác sampling bệnh viện YHCT",
        status: "Đề xuất mới",
        metric: "Reach 2.1K khách/th",
        period: "Q3/2026",
        owner: "Partnership",
      },
    ],
    forecasts: [
      {
        id: "in-f-1",
        name: "Doanh thu toàn mạng Q2",
        status: "Dự báo",
        metric: "+12% so Q1",
        period: "Q2/2026",
        owner: "FP&A",
      },
      {
        id: "in-f-2",
        name: "Nhu cầu GLH-DETOX-B",
        status: "Dự báo",
        metric: "+18% khối lượng",
        period: "Tháng 4–6/2026",
        owner: "Demand planning",
      },
      {
        id: "in-f-3",
        name: "Tồn kho tối ưu tháng 6",
        status: "Mô hình",
        metric: "DSO 32 ngày",
        period: "T6/2026",
        owner: "Supply chain",
      },
      {
        id: "in-f-4",
        name: "Hiệu quả trade spend",
        status: "Dự báo",
        metric: "ROI 3.1× trung bình",
        period: "Q2/2026",
        owner: "Trade finance",
      },
      {
        id: "in-f-5",
        name: "Lưu lượng khách cuối tuần",
        status: "Dự báo",
        metric: "+6% footfall",
        period: "T4–T5/2026",
        owner: "Ops analytics",
      },
    ],
    recommendations: [
      {
        id: "in-rec-1",
        name: "Tăng facing GLH-4412 tại TOP 8 CH",
        status: "Khuyến nghị",
        metric: "Ưu tiên 1",
        period: "Trong 2 tuần",
        owner: "Trade steering",
      },
      {
        id: "in-rec-2",
        name: "Điều chỉnh KM vùng Đà Nẵng",
        status: "Khuyến nghị",
        metric: "Giảm −5% giá kệ",
        period: "Tuần 13/2026",
        owner: "Pricing",
      },
      {
        id: "in-rec-3",
        name: "Đào tạo lại script upsell detox",
        status: "Khuyến nghị",
        metric: "6 CH điểm thấp",
        period: "Tháng 4/2026",
        owner: "Đào tạo",
      },
      {
        id: "in-rec-4",
        name: "Chuyển tồn GLH-120 Bắc → Nam",
        status: "Khuyến nghị",
        metric: "Giảm tồn chậm 20%",
        period: "Tháng 3/2026",
        owner: "Kho trung tâm",
      },
      {
        id: "in-rec-5",
        name: "Tăng ngân sách digital coupon",
        status: "Xem xét",
        metric: "ROI > 3×",
        period: "Q2/2026",
        owner: "Marketing mix",
      },
    ],
  },
};
