import type { HeritageModuleData } from "@/types/heritage";

export const heritageMockZh: HeritageModuleData = {
  tradeMarketing: {
    merchandiseDisplay: [
      {
        id: "tm-md-1",
        name: "中医药传承陈列角",
        status: "进行中",
        metric: "区域销售+22%",
        period: "2026年Q1",
        owner: "陈列与理货",
      },
      {
        id: "tm-md-2",
        name: "A货架 — 药茶与药材",
        status: "进行中",
        metric: "排面+2 · 28店",
        period: "2026年3月",
        owner: "陈列团队",
      },
      {
        id: "tm-md-3",
        name: "主货架立牌 — 上山茶",
        status: "已完成",
        metric: "合规率96%",
        period: "2025年Q4",
        owner: "贸易运营",
      },
      {
        id: "tm-md-4",
        name: "新价签与货架插卡",
        status: "计划中",
        metric: "36/36店更新",
        period: "2026/04/01",
        owner: "贸易运营",
      },
      {
        id: "tm-md-5",
        name: "Yogi Food陈列审计",
        status: "监控中",
        metric: "3店需调整排面",
        period: "2026年第13周",
        owner: "南部督导",
      },
    ],
    salesTraining: [
      {
        id: "tm-st-1",
        name: "POS培训 — 药茶搭售话术",
        status: "进行中",
        metric: "稽核88/100",
        period: "2026年Q2",
        owner: "门店培训",
      },
      {
        id: "tm-st-2",
        name: "中成药OTC柜台工作坊",
        status: "进行中",
        metric: "124名员工完成",
        period: "2026年3月",
        owner: "产品培训",
      },
      {
        id: "tm-st-3",
        name: "线上学习 — Yogi Food营养零食",
        status: "计划中",
        metric: "目标200人",
        period: "2026年Q2",
        owner: "Yogi Food贸易",
      },
      {
        id: "tm-st-4",
        name: "周末班次技能检查",
        status: "监控中",
        metric: "4店低于75分",
        period: "2026年第12周",
        owner: "北部督导",
      },
      {
        id: "tm-st-5",
        name: "新员工入职 — 迎宾话术",
        status: "已完成",
        metric: "42人 · 通过率95%",
        period: "2026年Q2",
        owner: "人力与培训",
      },
    ],
    customerCare: [
      {
        id: "tm-cc-1",
        name: "金卡客户激活",
        status: "进行中",
        metric: "复购+9%",
        period: "持续",
        owner: "CRM与贸易",
      },
      {
        id: "tm-cc-2",
        name: "购后7天关怀计划",
        status: "进行中",
        metric: "满意度4.6/5",
        period: "2026年3月",
        owner: "客户关怀",
      },
      {
        id: "tm-cc-3",
        name: "柜台客服热线 — 投诉话术",
        status: "已完成",
        metric: "处理时长−18%",
        period: "2026年Q1",
        owner: "门店运营",
      },
      {
        id: "tm-cc-4",
        name: "VIP生日礼遇",
        status: "计划中",
        metric: "目标客户2.1K",
        period: "2026年Q2",
        owner: "CRM",
      },
      {
        id: "tm-cc-5",
        name: "药茶试饮反馈亭",
        status: "监控中",
        metric: "NPS 68",
        period: "2026年第12–16周",
        owner: "现场激活",
      },
    ],
    salesPolicy: [
      {
        id: "tm-sp-1",
        name: "中成药ETC周末八五折",
        status: "进行中",
        metric: "销售提升11%",
        period: "2026年3月",
        owner: "定价与贸易",
      },
      {
        id: "tm-sp-2",
        name: "药茶买二赠一",
        status: "进行中",
        metric: "连带2.4 SKU/单",
        period: "2026年3月",
        owner: "贸易 — 中部",
      },
      {
        id: "tm-sp-3",
        name: "中成药经销商折扣政策",
        status: "进行中",
        metric: "124家经销商",
        period: "2026年",
        owner: "专业渠道",
      },
      {
        id: "tm-sp-4",
        name: "退货额度 — 上山茶",
        status: "监控中",
        metric: "退货率1.2%",
        period: "持续",
        owner: "贸易政策",
      },
      {
        id: "tm-sp-5",
        name: "明码标价更新 — Q2 rollout",
        status: "计划中",
        metric: "全网络36店",
        period: "2026/04/01",
        owner: "定价",
      },
    ],
    seasonalCampaigns: [
      {
        id: "tm-sc-1",
        name: "2026春节门店陈列",
        status: "已完成",
        metric: "ROI 3.8×",
        period: "2026年Q1",
        owner: "贸易组 — 北部",
      },
      {
        id: "tm-sc-2",
        name: "柜台草本试饮",
        status: "进行中",
        metric: "转化率18%",
        period: "2026年第12–16周",
        owner: "现场激活",
      },
      {
        id: "tm-sc-3",
        name: "河内仓4小时闪购",
        status: "已完成",
        metric: "门店库存售出87%",
        period: "2026/02/15",
        owner: "仓储与贸易河内",
      },
      {
        id: "tm-sc-4",
        name: "春节礼盒 — 迷你药茶套装",
        status: "已完成",
        metric: "促销NPS 72",
        period: "2026年Q1",
        owner: "品牌激活",
      },
      {
        id: "tm-sc-5",
        name: "夏季战役 — 咖啡与水果",
        status: "计划中",
        metric: "预算₫240M",
        period: "2026年5–7月",
        owner: "总部贸易营销",
      },
    ],
    newStoreOpening: [
      {
        id: "tm-no-1",
        name: "岘港02店开业",
        status: "进行中",
        metric: "首周销售₫186M",
        period: "2026年3月",
        owner: "网络拓展",
      },
      {
        id: "tm-no-2",
        name: "开业周POS清单推广",
        status: "进行中",
        metric: "完成率94%",
        period: "2026年第12周",
        owner: "中部督导",
      },
      {
        id: "tm-no-3",
        name: "新店陈列套装 — 12 SKU",
        status: "计划中",
        metric: "42套就绪",
        period: "2026年Q2",
        owner: "陈列与理货",
      },
      {
        id: "tm-no-4",
        name: "现场开业培训 — 3天",
        status: "计划中",
        metric: "18人/期",
        period: "2026年4月",
        owner: "门店培训",
      },
      {
        id: "tm-no-5",
        name: "上山茶旗舰店盛大开业",
        status: "监控中",
        metric: "客流3.2K/天",
        period: "2026/05/15",
        owner: "上山茶贸易",
      },
    ],
  },
  insights: {
    risks: [
      {
        id: "in-r-1",
        name: "GLH-120滞销 — 南部",
        status: "高",
        metric: "库存>45天",
        period: "今日更新",
        owner: "仓储与供应",
      },
      {
        id: "in-r-2",
        name: "岘港竞品价格战",
        status: "中",
        metric: "货架价−8%",
        period: "2026年第11周",
        owner: "贸易情报",
      },
      {
        id: "in-r-3",
        name: "周末班次人手不足",
        status: "高",
        metric: "4店预警",
        period: "下周末",
        owner: "门店运营",
      },
      {
        id: "in-r-4",
        name: "POS促销执行偏差",
        status: "监控中",
        metric: "3%订单价格错误",
        period: "2026年3月",
        owner: "内审",
      },
      {
        id: "in-r-5",
        name: "GLH-DETOX-B断货风险",
        status: "中",
        metric: "覆盖9天",
        period: "14天预测",
        owner: "需求计划",
      },
    ],
    opportunities: [
      {
        id: "in-o-1",
        name: "排毒+洗发水组合交叉销售",
        status: "高优先级",
        metric: "潜力+₫320M/月",
        period: "2026年Q2",
        owner: "品类与贸易",
      },
      {
        id: "in-o-2",
        name: "春节后金卡客户复购",
        status: "推进中",
        metric: "目标客户12K",
        period: "2026年3–4月",
        owner: "CRM",
      },
      {
        id: "in-o-3",
        name: "胡志明主货架排面扩展",
        status: "新提案",
        metric: "预计提升+15%",
        period: "2026年Q2",
        owner: "陈列",
      },
      {
        id: "in-o-4",
        name: "线上下单 — 门店自提",
        status: "推进中",
        metric: "占比8%→12%",
        period: "6个月",
        owner: "全渠道",
      },
      {
        id: "in-o-5",
        name: "中医院试饮合作",
        status: "新提案",
        metric: "触达2.1K人/月",
        period: "2026年Q3",
        owner: "合作拓展",
      },
    ],
    forecasts: [
      {
        id: "in-f-1",
        name: "全网络Q2营收",
        status: "预测",
        metric: "较Q1+12%",
        period: "2026年Q2",
        owner: "财务规划",
      },
      {
        id: "in-f-2",
        name: "GLH-DETOX-B需求",
        status: "预测",
        metric: "销量+18%",
        period: "2026年4–6月",
        owner: "需求计划",
      },
      {
        id: "in-f-3",
        name: "6月最优库存",
        status: "模型",
        metric: "DSO 32天",
        period: "2026年6月",
        owner: "供应链",
      },
      {
        id: "in-f-4",
        name: "贸易费用效率",
        status: "预测",
        metric: "平均ROI 3.1×",
        period: "2026年Q2",
        owner: "贸易财务",
      },
      {
        id: "in-f-5",
        name: "周末客流",
        status: "预测",
        metric: "客流+6%",
        period: "2026年4–5月",
        owner: "运营分析",
      },
    ],
    recommendations: [
      {
        id: "in-rec-1",
        name: "TOP 8店增加GLH-4412排面",
        status: "建议",
        metric: "优先级1",
        period: "2周内",
        owner: "贸易指导组",
      },
      {
        id: "in-rec-2",
        name: "调整岘港促销",
        status: "建议",
        metric: "货架价−5%",
        period: "2026年第13周",
        owner: "定价",
      },
      {
        id: "in-rec-3",
        name: "复训排毒搭售话术",
        status: "建议",
        metric: "6店低分",
        period: "2026年4月",
        owner: "培训",
      },
      {
        id: "in-rec-4",
        name: "GLH-120库存北→南调拨",
        status: "建议",
        metric: "滞销−20%",
        period: "2026年3月",
        owner: "中央仓",
      },
      {
        id: "in-rec-5",
        name: "增加数字优惠券预算",
        status: "审议中",
        metric: "ROI > 3×",
        period: "2026年Q2",
        owner: "营销组合",
      },
    ],
  },
};
